# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XBART_cpp <- function(y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin = 1L, mtry = 0L, p_categorical = 0L, kap = 16, s = 4, tau_kap = 3, tau_s = 0.5, verbose = FALSE, sampling_tau = TRUE, parallel = TRUE, set_random_seed = FALSE, random_seed = 0L, sample_weights_flag = TRUE, nthread = 0) {
    .Call(`_XBART_XBART_cpp`, y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin, mtry, p_categorical, kap, s, tau_kap, tau_s, verbose, sampling_tau, parallel, set_random_seed, random_seed, sample_weights_flag, nthread)
}

XBART_multinomial_cpp <- function(y, num_class, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau_a, tau_b, no_split_penality, burnin = 1L, mtry = 0L, p_categorical = 0L, verbose = FALSE, parallel = TRUE, set_random_seed = FALSE, random_seed = 0L, sample_weights_flag = TRUE, separate_tree = FALSE, weight = 1, update_weight = TRUE, update_tau = TRUE, nthread = 0, hmult = 1, heps = 0.1) {
    .Call(`_XBART_XBART_multinomial_cpp`, y, num_class, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau_a, tau_b, no_split_penality, burnin, mtry, p_categorical, verbose, parallel, set_random_seed, random_seed, sample_weights_flag, separate_tree, weight, update_weight, update_tau, nthread, hmult, heps)
}

XBART_Probit_cpp <- function(y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin = 1L, mtry = 0L, p_categorical = 0L, kap = 16, s = 4, verbose = FALSE, parallel = TRUE, set_random_seed = FALSE, random_seed = 0L, sample_weights_flag = TRUE, nthread = 0) {
    .Call(`_XBART_XBART_Probit_cpp`, y, X, Xtest, num_trees, num_sweeps, max_depth, n_min, num_cutpoints, alpha, beta, tau, no_split_penality, burnin, mtry, p_categorical, kap, s, verbose, parallel, set_random_seed, random_seed, sample_weights_flag, nthread)
}

xbart_predict <- function(X, y_mean, tree_pnt) {
    .Call(`_XBART_xbart_predict`, X, y_mean, tree_pnt)
}

xbart_multinomial_predict <- function(X, y_mean, num_class, tree_pnt, iteration) {
    .Call(`_XBART_xbart_multinomial_predict`, X, y_mean, num_class, tree_pnt, iteration)
}

xbart_multinomial_predict_3D <- function(X, y_mean, num_class, tree_pnt, iteration) {
    .Call(`_XBART_xbart_multinomial_predict_3D`, X, y_mean, num_class, tree_pnt, iteration)
}

r_to_json <- function(y_mean, tree_pnt) {
    .Call(`_XBART_r_to_json`, y_mean, tree_pnt)
}

json_to_r <- function(json_string_r) {
    .Call(`_XBART_json_to_r`, json_string_r)
}

r_to_json_3D <- function(tree_pnt) {
    .Call(`_XBART_r_to_json_3D`, tree_pnt)
}

json_to_r_3D <- function(json_string_r) {
    .Call(`_XBART_json_to_r_3D`, json_string_r)
}

sample_int_crank <- function(n, size, prob) {
    .Call(`_XBART_sample_int_crank`, n, size, prob)
}

sample_int_ccrank <- function(n, size, prob) {
    .Call(`_XBART_sample_int_ccrank`, n, size, prob)
}

sample_int_expj <- function(n, size, prob) {
    .Call(`_XBART_sample_int_expj`, n, size, prob)
}

sample_int_expjs <- function(n, size, prob) {
    .Call(`_XBART_sample_int_expjs`, n, size, prob)
}

