# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_tree_std <- function(trees, Xnew) {
    .Call(`_abarth_predict_tree_std`, trees, Xnew)
}

predict_tree <- function(trees, Xnew) {
    .Call(`_abarth_predict_tree`, trees, Xnew)
}

train_forest_root_all <- function(y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry = 0L, draw_sigma = FALSE, kap = 16, s = 4, verbose = FALSE, m_update_sigma = FALSE, draw_mu = FALSE, parallel = TRUE) {
    .Call(`_abarth_train_forest_root_all`, y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry, draw_sigma, kap, s, verbose, m_update_sigma, draw_mu, parallel)
}

train_forest_root_std_newXorder <- function(y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry = 0L, draw_sigma = FALSE, kap = 16, s = 4, verbose = FALSE, m_update_sigma = FALSE, draw_mu = FALSE, parallel = TRUE) {
    .Call(`_abarth_train_forest_root_std_newXorder`, y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry, draw_sigma, kap, s, verbose, m_update_sigma, draw_mu, parallel)
}

train_forest_root_std_old <- function(y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry = 0L, draw_sigma = FALSE, kap = 16, s = 4, verbose = FALSE, m_update_sigma = FALSE, draw_mu = FALSE, parallel = TRUE) {
    .Call(`_abarth_train_forest_root_std_old`, y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry, draw_sigma, kap, s, verbose, m_update_sigma, draw_mu, parallel)
}

train_forest_root_std <- function(y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry = 0L, draw_sigma = FALSE, kap = 16, s = 4, verbose = FALSE, m_update_sigma = FALSE, draw_mu = FALSE, parallel = TRUE) {
    .Call(`_abarth_train_forest_root_std`, y, X, Xtest, M, K, L, N_sweeps, max_depth, Nmin, Ncutpoints, alpha, beta, tau, mtry, draw_sigma, kap, s, verbose, m_update_sigma, draw_mu, parallel)
}

